/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jpi2;

/**
 *
 * @author ffutigam
 */
public class MenuEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuEmpresa() {
        initComponents();
        MetodosTelas.centralizar(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        btnConsultarVagas = new javax.swing.JButton();
        btnCadastrarVagas = new javax.swing.JButton();
        btnPendencias = new javax.swing.JButton();
        btnVisualizarCurriculos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label1.setText("Menu");

        btnConsultarVagas.setText("Consultar Vagas");
        btnConsultarVagas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarVagasMouseClicked(evt);
            }
        });

        btnCadastrarVagas.setText("Cadastrar Vagas");
        btnCadastrarVagas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarVagasMouseClicked(evt);
            }
        });

        btnPendencias.setText("Pendências");
        btnPendencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPendenciasMouseClicked(evt);
            }
        });

        btnVisualizarCurriculos.setText("Visualizar Currículos");
        btnVisualizarCurriculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVisualizarCurriculosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVisualizarCurriculos)
                            .addComponent(btnConsultarVagas)
                            .addComponent(btnCadastrarVagas)
                            .addComponent(btnPendencias))
                        .addGap(163, 225, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarVagas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrarVagas)
                .addGap(12, 12, 12)
                .addComponent(btnPendencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVisualizarCurriculos)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarVagasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarVagasMouseClicked
        new ConsultarVagas().setVisible(true);

    }//GEN-LAST:event_btnConsultarVagasMouseClicked

    private void btnCadastrarVagasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarVagasMouseClicked
        new CadastrarVagas().setVisible(true);

    }//GEN-LAST:event_btnCadastrarVagasMouseClicked

    private void btnPendenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPendenciasMouseClicked
        new Pendencias().setVisible(true);

    }//GEN-LAST:event_btnPendenciasMouseClicked

    private void btnVisualizarCurriculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisualizarCurriculosMouseClicked
        new VisualizarCurriculos().setVisible(true);

    }//GEN-LAST:event_btnVisualizarCurriculosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEmpresa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarVagas;
    private javax.swing.JButton btnConsultarVagas;
    private javax.swing.JButton btnPendencias;
    private javax.swing.JButton btnVisualizarCurriculos;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
