/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

/**
 *
 * @author ffutigam
 */
public class MenuAdm extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdm
     */
    public MenuAdm() {
        initComponents();
        MetodosTelas.centralizar(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManutencaoAreaAtuacao = new javax.swing.JButton();
        btnManutencaoEmpresas = new javax.swing.JButton();
        btnManutencaoUniversidades = new javax.swing.JButton();
        btnManutencaoCursos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuPrincipal = new javax.swing.JMenu();
        MnuManutencaoUniversidades = new javax.swing.JMenuItem();
        MnuManutencaoEmpresas = new javax.swing.JMenuItem();
        MnuManutencaoCursos = new javax.swing.JMenuItem();
        MnuManutencaoAreaAtuacao = new javax.swing.JMenuItem();
        MnuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu para Administrador do Sistema");
        setResizable(false);

        btnManutencaoAreaAtuacao.setText("Manutenção das Áreas de Atuação");
        btnManutencaoAreaAtuacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManutencaoAreaAtuacaoMouseClicked(evt);
            }
        });

        btnManutencaoEmpresas.setText("Manutenção das Empresas");
        btnManutencaoEmpresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManutencaoEmpresasMouseClicked(evt);
            }
        });

        btnManutencaoUniversidades.setText("Manutenção das Universidades");
        btnManutencaoUniversidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManutencaoUniversidadesMouseClicked(evt);
            }
        });

        btnManutencaoCursos.setText("Manutenção dos Cursos");
        btnManutencaoCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManutencaoCursosMouseClicked(evt);
            }
        });

        MnuPrincipal.setText("Telas de Manutenção de Cadastros");

        MnuManutencaoUniversidades.setText("Manutenção de Universidades");
        MnuManutencaoUniversidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnuManutencaoUniversidadesMouseClicked(evt);
            }
        });
        MnuManutencaoUniversidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuManutencaoUniversidadesActionPerformed(evt);
            }
        });
        MnuPrincipal.add(MnuManutencaoUniversidades);

        MnuManutencaoEmpresas.setText("Manutenção de Empresas");
        MnuManutencaoEmpresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnuManutencaoEmpresasMouseClicked(evt);
            }
        });
        MnuManutencaoEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuManutencaoEmpresasActionPerformed(evt);
            }
        });
        MnuPrincipal.add(MnuManutencaoEmpresas);

        MnuManutencaoCursos.setText("Manutenção de Cursos");
        MnuManutencaoCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnuManutencaoCursosMouseClicked(evt);
            }
        });
        MnuManutencaoCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuManutencaoCursosActionPerformed(evt);
            }
        });
        MnuPrincipal.add(MnuManutencaoCursos);

        MnuManutencaoAreaAtuacao.setText("Manutenção de Áreas de Atuação");
        MnuManutencaoAreaAtuacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnuManutencaoAreaAtuacaoMouseClicked(evt);
            }
        });
        MnuManutencaoAreaAtuacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuManutencaoAreaAtuacaoActionPerformed(evt);
            }
        });
        MnuManutencaoAreaAtuacao.addMenuDragMouseListener(new javax.swing.event.MenuDragMouseListener() {
            public void menuDragMouseReleased(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseDragged(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseEntered(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseExited(javax.swing.event.MenuDragMouseEvent evt) {
                MnuManutencaoAreaAtuacaoMenuDragMouseExited(evt);
            }
        });
        MnuPrincipal.add(MnuManutencaoAreaAtuacao);

        jMenuBar1.add(MnuPrincipal);

        MnuSair.setText("Sair");
        jMenuBar1.add(MnuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManutencaoAreaAtuacao)
                    .addComponent(btnManutencaoEmpresas)
                    .addComponent(btnManutencaoUniversidades)
                    .addComponent(btnManutencaoCursos))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnManutencaoAreaAtuacao)
                .addGap(28, 28, 28)
                .addComponent(btnManutencaoEmpresas)
                .addGap(31, 31, 31)
                .addComponent(btnManutencaoUniversidades)
                .addGap(35, 35, 35)
                .addComponent(btnManutencaoCursos)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuManutencaoAreaAtuacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuManutencaoAreaAtuacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnuManutencaoAreaAtuacaoActionPerformed

    private void MnuManutencaoUniversidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuManutencaoUniversidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnuManutencaoUniversidadesActionPerformed

    private void MnuManutencaoUniversidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnuManutencaoUniversidadesMouseClicked
        new ManutencaoUniversidade().setVisible(true);
    }//GEN-LAST:event_MnuManutencaoUniversidadesMouseClicked

    private void MnuManutencaoEmpresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnuManutencaoEmpresasMouseClicked
        new ManutencaoEmpresa().setVisible(true);
    }//GEN-LAST:event_MnuManutencaoEmpresasMouseClicked

    private void MnuManutencaoAreaAtuacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnuManutencaoAreaAtuacaoMouseClicked
        new ManutencaoAreaAtuacao().setVisible(true);
    }//GEN-LAST:event_MnuManutencaoAreaAtuacaoMouseClicked

    private void MnuManutencaoCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnuManutencaoCursosMouseClicked
        new ManutencaoCurso().setVisible(true);
    }//GEN-LAST:event_MnuManutencaoCursosMouseClicked

    private void MnuManutencaoEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuManutencaoEmpresasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnuManutencaoEmpresasActionPerformed

    private void MnuManutencaoCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuManutencaoCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnuManutencaoCursosActionPerformed

    private void MnuManutencaoAreaAtuacaoMenuDragMouseExited(javax.swing.event.MenuDragMouseEvent evt) {//GEN-FIRST:event_MnuManutencaoAreaAtuacaoMenuDragMouseExited
        new ManutencaoAreaAtuacao().setVisible(true);
    }//GEN-LAST:event_MnuManutencaoAreaAtuacaoMenuDragMouseExited

    private void btnManutencaoAreaAtuacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManutencaoAreaAtuacaoMouseClicked
        new ManutencaoAreaAtuacao().setVisible(true);
    }//GEN-LAST:event_btnManutencaoAreaAtuacaoMouseClicked

    private void btnManutencaoEmpresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManutencaoEmpresasMouseClicked
        new ManutencaoEmpresa().setVisible(true);
    }//GEN-LAST:event_btnManutencaoEmpresasMouseClicked

    private void btnManutencaoUniversidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManutencaoUniversidadesMouseClicked
        new ManutencaoUniversidade().setVisible(true);
    }//GEN-LAST:event_btnManutencaoUniversidadesMouseClicked

    private void btnManutencaoCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManutencaoCursosMouseClicked
        new ManutencaoCurso().setVisible(true);
    }//GEN-LAST:event_btnManutencaoCursosMouseClicked
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnuManutencaoAreaAtuacao;
    private javax.swing.JMenuItem MnuManutencaoCursos;
    private javax.swing.JMenuItem MnuManutencaoEmpresas;
    public javax.swing.JMenuItem MnuManutencaoUniversidades;
    private javax.swing.JMenu MnuPrincipal;
    private javax.swing.JMenu MnuSair;
    private javax.swing.JButton btnManutencaoAreaAtuacao;
    private javax.swing.JButton btnManutencaoCursos;
    private javax.swing.JButton btnManutencaoEmpresas;
    private javax.swing.JButton btnManutencaoUniversidades;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
