package Map;
// Generated Sep 16, 2012 5:53:47 PM by Hibernate Tools 3.2.1.GA



/**
 * AreaAtuacaoSistema generated by hbm2java
 */
public class AreaAtuacaoSistema  implements java.io.Serializable {


     private int codAreaAtuacao;
     private String descricao;
     private int fk1CodCv;

    public AreaAtuacaoSistema() {
    }

	
    public AreaAtuacaoSistema(int codAreaAtuacao, int fk1CodCv) {
        this.codAreaAtuacao = codAreaAtuacao;
        this.fk1CodCv = fk1CodCv;
    }
    public AreaAtuacaoSistema(int codAreaAtuacao, String descricao, int fk1CodCv) {
       this.codAreaAtuacao = codAreaAtuacao;
       this.descricao = descricao;
       this.fk1CodCv = fk1CodCv;
    }
   
    public int getCodAreaAtuacao() {
        return this.codAreaAtuacao;
    }
    
    public void setCodAreaAtuacao(int codAreaAtuacao) {
        this.codAreaAtuacao = codAreaAtuacao;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public int getFk1CodCv() {
        return this.fk1CodCv;
    }
    
    public void setFk1CodCv(int fk1CodCv) {
        this.fk1CodCv = fk1CodCv;
    }




}


