package Map;
// Generated Sep 16, 2012 5:53:47 PM by Hibernate Tools 3.2.1.GA



/**
 * Curriculo generated by hbm2java
 */
public class Curriculo  implements java.io.Serializable {


     private int codCv;
     private Integer expProf;
     private Integer cerficado;
     private int codAreaAtuacao;
     private int fk1CodUsr;

    public Curriculo() {
    }

	
    public Curriculo(int codCv, int codAreaAtuacao, int fk1CodUsr) {
        this.codCv = codCv;
        this.codAreaAtuacao = codAreaAtuacao;
        this.fk1CodUsr = fk1CodUsr;
    }
    public Curriculo(int codCv, Integer expProf, Integer cerficado, int codAreaAtuacao, int fk1CodUsr) {
       this.codCv = codCv;
       this.expProf = expProf;
       this.cerficado = cerficado;
       this.codAreaAtuacao = codAreaAtuacao;
       this.fk1CodUsr = fk1CodUsr;
    }
   
    public int getCodCv() {
        return this.codCv;
    }
    
    public void setCodCv(int codCv) {
        this.codCv = codCv;
    }
    public Integer getExpProf() {
        return this.expProf;
    }
    
    public void setExpProf(Integer expProf) {
        this.expProf = expProf;
    }
    public Integer getCerficado() {
        return this.cerficado;
    }
    
    public void setCerficado(Integer cerficado) {
        this.cerficado = cerficado;
    }
    public int getCodAreaAtuacao() {
        return this.codAreaAtuacao;
    }
    
    public void setCodAreaAtuacao(int codAreaAtuacao) {
        this.codAreaAtuacao = codAreaAtuacao;
    }
    public int getFk1CodUsr() {
        return this.fk1CodUsr;
    }
    
    public void setFk1CodUsr(int fk1CodUsr) {
        this.fk1CodUsr = fk1CodUsr;
    }




}


