package Map;
// Generated Sep 16, 2012 5:53:47 PM by Hibernate Tools 3.2.1.GA



/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private int codCurso;
     private String descricao;
     private int fk1CodUniversidade;

    public Curso() {
    }

	
    public Curso(int codCurso, int fk1CodUniversidade) {
        this.codCurso = codCurso;
        this.fk1CodUniversidade = fk1CodUniversidade;
    }
    public Curso(int codCurso, String descricao, int fk1CodUniversidade) {
       this.codCurso = codCurso;
       this.descricao = descricao;
       this.fk1CodUniversidade = fk1CodUniversidade;
    }
   
    public int getCodCurso() {
        return this.codCurso;
    }
    
    public void setCodCurso(int codCurso) {
        this.codCurso = codCurso;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public int getFk1CodUniversidade() {
        return this.fk1CodUniversidade;
    }
    
    public void setFk1CodUniversidade(int fk1CodUniversidade) {
        this.fk1CodUniversidade = fk1CodUniversidade;
    }




}


