package Map;
// Generated Sep 16, 2012 5:53:47 PM by Hibernate Tools 3.2.1.GA



/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private int codEmpresa;
     private String cnpj;
     private int nome;
     private String senha;
     private int fk1ExpProf;

    public Empresa() {
    }

    public Empresa(int codEmpresa, String cnpj, int nome, String senha, int fk1ExpProf) {
       this.codEmpresa = codEmpresa;
       this.cnpj = cnpj;
       this.nome = nome;
       this.senha = senha;
       this.fk1ExpProf = fk1ExpProf;
    }
   
    public int getCodEmpresa() {
        return this.codEmpresa;
    }
    
    public void setCodEmpresa(int codEmpresa) {
        this.codEmpresa = codEmpresa;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public int getNome() {
        return this.nome;
    }
    
    public void setNome(int nome) {
        this.nome = nome;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public int getFk1ExpProf() {
        return this.fk1ExpProf;
    }
    
    public void setFk1ExpProf(int fk1ExpProf) {
        this.fk1ExpProf = fk1ExpProf;
    }




}


