package Map;
// Generated Sep 16, 2012 5:53:47 PM by Hibernate Tools 3.2.1.GA



/**
 * ExpProfSistema generated by hbm2java
 */
public class ExpProfSistema  implements java.io.Serializable {


     private int expProf;
     private String descricao;
     private Integer codEmpresa;
     private int fk1CodCv;

    public ExpProfSistema() {
    }

	
    public ExpProfSistema(int expProf, int fk1CodCv) {
        this.expProf = expProf;
        this.fk1CodCv = fk1CodCv;
    }
    public ExpProfSistema(int expProf, String descricao, Integer codEmpresa, int fk1CodCv) {
       this.expProf = expProf;
       this.descricao = descricao;
       this.codEmpresa = codEmpresa;
       this.fk1CodCv = fk1CodCv;
    }
   
    public int getExpProf() {
        return this.expProf;
    }
    
    public void setExpProf(int expProf) {
        this.expProf = expProf;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Integer getCodEmpresa() {
        return this.codEmpresa;
    }
    
    public void setCodEmpresa(Integer codEmpresa) {
        this.codEmpresa = codEmpresa;
    }
    public int getFk1CodCv() {
        return this.fk1CodCv;
    }
    
    public void setFk1CodCv(int fk1CodCv) {
        this.fk1CodCv = fk1CodCv;
    }




}


