package Map;
// Generated Sep 16, 2012 5:53:47 PM by Hibernate Tools 3.2.1.GA



/**
 * FormacaoAcademica generated by hbm2java
 */
public class FormacaoAcademica  implements java.io.Serializable {


     private int codFa;
     private int codUsr;
     private int codUniversidade;
     private String situacao;
     private int semestreAtual;
     private int semestreFormacao;
     private int anoFormacao;
     private int fk1CodUsr;

    public FormacaoAcademica() {
    }

    public FormacaoAcademica(int codFa, int codUsr, int codUniversidade, String situacao, int semestreAtual, int semestreFormacao, int anoFormacao, int fk1CodUsr) {
       this.codFa = codFa;
       this.codUsr = codUsr;
       this.codUniversidade = codUniversidade;
       this.situacao = situacao;
       this.semestreAtual = semestreAtual;
       this.semestreFormacao = semestreFormacao;
       this.anoFormacao = anoFormacao;
       this.fk1CodUsr = fk1CodUsr;
    }
   
    public int getCodFa() {
        return this.codFa;
    }
    
    public void setCodFa(int codFa) {
        this.codFa = codFa;
    }
    public int getCodUsr() {
        return this.codUsr;
    }
    
    public void setCodUsr(int codUsr) {
        this.codUsr = codUsr;
    }
    public int getCodUniversidade() {
        return this.codUniversidade;
    }
    
    public void setCodUniversidade(int codUniversidade) {
        this.codUniversidade = codUniversidade;
    }
    public String getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }
    public int getSemestreAtual() {
        return this.semestreAtual;
    }
    
    public void setSemestreAtual(int semestreAtual) {
        this.semestreAtual = semestreAtual;
    }
    public int getSemestreFormacao() {
        return this.semestreFormacao;
    }
    
    public void setSemestreFormacao(int semestreFormacao) {
        this.semestreFormacao = semestreFormacao;
    }
    public int getAnoFormacao() {
        return this.anoFormacao;
    }
    
    public void setAnoFormacao(int anoFormacao) {
        this.anoFormacao = anoFormacao;
    }
    public int getFk1CodUsr() {
        return this.fk1CodUsr;
    }
    
    public void setFk1CodUsr(int fk1CodUsr) {
        this.fk1CodUsr = fk1CodUsr;
    }




}


