package Map;
// Generated Sep 16, 2012 5:53:47 PM by Hibernate Tools 3.2.1.GA



/**
 * Universidade generated by hbm2java
 */
public class Universidade  implements java.io.Serializable {


     private int codUniversidade;
     private String nome;
     private int codCurso;
     private int fk1CodFa;

    public Universidade() {
    }

	
    public Universidade(int codUniversidade, int codCurso, int fk1CodFa) {
        this.codUniversidade = codUniversidade;
        this.codCurso = codCurso;
        this.fk1CodFa = fk1CodFa;
    }
    public Universidade(int codUniversidade, String nome, int codCurso, int fk1CodFa) {
       this.codUniversidade = codUniversidade;
       this.nome = nome;
       this.codCurso = codCurso;
       this.fk1CodFa = fk1CodFa;
    }
   
    public int getCodUniversidade() {
        return this.codUniversidade;
    }
    
    public void setCodUniversidade(int codUniversidade) {
        this.codUniversidade = codUniversidade;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public int getCodCurso() {
        return this.codCurso;
    }
    
    public void setCodCurso(int codCurso) {
        this.codCurso = codCurso;
    }
    public int getFk1CodFa() {
        return this.fk1CodFa;
    }
    
    public void setFk1CodFa(int fk1CodFa) {
        this.fk1CodFa = fk1CodFa;
    }




}


