package Map;
// Generated Sep 16, 2012 5:53:47 PM by Hibernate Tools 3.2.1.GA



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int codUsr;
     private String cpf;
     private String nome;
     private String senha;
     private Integer codCv;
     private int codFa;

    public Usuario() {
    }

	
    public Usuario(int codUsr, String cpf, String nome, String senha, int codFa) {
        this.codUsr = codUsr;
        this.cpf = cpf;
        this.nome = nome;
        this.senha = senha;
        this.codFa = codFa;
    }
    public Usuario(int codUsr, String cpf, String nome, String senha, Integer codCv, int codFa) {
       this.codUsr = codUsr;
       this.cpf = cpf;
       this.nome = nome;
       this.senha = senha;
       this.codCv = codCv;
       this.codFa = codFa;
    }
   
    public int getCodUsr() {
        return this.codUsr;
    }
    
    public void setCodUsr(int codUsr) {
        this.codUsr = codUsr;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Integer getCodCv() {
        return this.codCv;
    }
    
    public void setCodCv(Integer codCv) {
        this.codCv = codCv;
    }
    public int getCodFa() {
        return this.codFa;
    }
    
    public void setCodFa(int codFa) {
        this.codFa = codFa;
    }




}


