package Map;
// Generated Sep 16, 2012 5:53:47 PM by Hibernate Tools 3.2.1.GA



/**
 * VagasId generated by hbm2java
 */
public class VagasId  implements java.io.Serializable {


     private int codVaga;
     private int fk2CodAreaAtuacao;

    public VagasId() {
    }

    public VagasId(int codVaga, int fk2CodAreaAtuacao) {
       this.codVaga = codVaga;
       this.fk2CodAreaAtuacao = fk2CodAreaAtuacao;
    }
   
    public int getCodVaga() {
        return this.codVaga;
    }
    
    public void setCodVaga(int codVaga) {
        this.codVaga = codVaga;
    }
    public int getFk2CodAreaAtuacao() {
        return this.fk2CodAreaAtuacao;
    }
    
    public void setFk2CodAreaAtuacao(int fk2CodAreaAtuacao) {
        this.fk2CodAreaAtuacao = fk2CodAreaAtuacao;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VagasId) ) return false;
		 VagasId castOther = ( VagasId ) other; 
         
		 return (this.getCodVaga()==castOther.getCodVaga())
 && (this.getFk2CodAreaAtuacao()==castOther.getFk2CodAreaAtuacao());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodVaga();
         result = 37 * result + this.getFk2CodAreaAtuacao();
         return result;
   }   


}


