package Map;
// Generated Sep 16, 2012 5:53:47 PM by Hibernate Tools 3.2.1.GA



/**
 * Vagas generated by hbm2java
 */
public class Vagas  implements java.io.Serializable {


     private VagasId id;
     private Integer salario;
     private String descricao;
     private int codEmpresa;
     private int codAreaAtuacao;
     private int fk1CodEmpresa;

    public Vagas() {
    }

	
    public Vagas(VagasId id, int codEmpresa, int codAreaAtuacao, int fk1CodEmpresa) {
        this.id = id;
        this.codEmpresa = codEmpresa;
        this.codAreaAtuacao = codAreaAtuacao;
        this.fk1CodEmpresa = fk1CodEmpresa;
    }
    public Vagas(VagasId id, Integer salario, String descricao, int codEmpresa, int codAreaAtuacao, int fk1CodEmpresa) {
       this.id = id;
       this.salario = salario;
       this.descricao = descricao;
       this.codEmpresa = codEmpresa;
       this.codAreaAtuacao = codAreaAtuacao;
       this.fk1CodEmpresa = fk1CodEmpresa;
    }
   
    public VagasId getId() {
        return this.id;
    }
    
    public void setId(VagasId id) {
        this.id = id;
    }
    public Integer getSalario() {
        return this.salario;
    }
    
    public void setSalario(Integer salario) {
        this.salario = salario;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public int getCodEmpresa() {
        return this.codEmpresa;
    }
    
    public void setCodEmpresa(int codEmpresa) {
        this.codEmpresa = codEmpresa;
    }
    public int getCodAreaAtuacao() {
        return this.codAreaAtuacao;
    }
    
    public void setCodAreaAtuacao(int codAreaAtuacao) {
        this.codAreaAtuacao = codAreaAtuacao;
    }
    public int getFk1CodEmpresa() {
        return this.fk1CodEmpresa;
    }
    
    public void setFk1CodEmpresa(int fk1CodEmpresa) {
        this.fk1CodEmpresa = fk1CodEmpresa;
    }




}


