package JPA2;
// Generated Oct 27, 2012 12:41:22 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AreaAtuacaoSistema generated by hbm2java
 */
@Entity
@Table(name="Area_Atuacao_Sistema"
    ,catalog="mack"
)
public class AreaAtuacaoSistema  implements java.io.Serializable {


     private int codAreaAtuacao;
     private String descricao;

    public AreaAtuacaoSistema() {
    }

	
    public AreaAtuacaoSistema(int codAreaAtuacao) {
        this.codAreaAtuacao = codAreaAtuacao;
    }
    public AreaAtuacaoSistema(int codAreaAtuacao, String descricao) {
       this.codAreaAtuacao = codAreaAtuacao;
       this.descricao = descricao;
    }
   
     @Id 
    
    @Column(name="Cod_Area_Atuacao", unique=true, nullable=false)
    public int getCodAreaAtuacao() {
        return this.codAreaAtuacao;
    }
    
    public void setCodAreaAtuacao(int codAreaAtuacao) {
        this.codAreaAtuacao = codAreaAtuacao;
    }
    
    @Column(name="Descricao", length=20)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


