package JPA2;
// Generated Nov 22, 2012 5:49:27 PM by Hibernate Tools 3.2.1.GA



/**
 * Curriculo generated by hbm2java
 */
public class Curriculo  implements java.io.Serializable {


     private Integer codCv;
     private Integer codExpProf;
     private String cerficado;
     private Integer codAreaAtuacao;
     private Integer codUsr;

    public Curriculo() {
    }

    public Curriculo(Integer codExpProf, String cerficado, Integer codAreaAtuacao, Integer codUsr) {
       this.codExpProf = codExpProf;
       this.cerficado = cerficado;
       this.codAreaAtuacao = codAreaAtuacao;
       this.codUsr = codUsr;
    }
   
    public Integer getCodCv() {
        return this.codCv;
    }
    
    public void setCodCv(Integer codCv) {
        this.codCv = codCv;
    }
    public Integer getCodExpProf() {
        return this.codExpProf;
    }
    
    public void setCodExpProf(Integer codExpProf) {
        this.codExpProf = codExpProf;
    }
    public String getCerficado() {
        return this.cerficado;
    }
    
    public void setCerficado(String cerficado) {
        this.cerficado = cerficado;
    }
    public Integer getCodAreaAtuacao() {
        return this.codAreaAtuacao;
    }
    
    public void setCodAreaAtuacao(Integer codAreaAtuacao) {
        this.codAreaAtuacao = codAreaAtuacao;
    }
    public Integer getCodUsr() {
        return this.codUsr;
    }
    
    public void setCodUsr(Integer codUsr) {
        this.codUsr = codUsr;
    }




}


