package JPA2;
// Generated Oct 27, 2012 7:04:32 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Curriculo generated by hbm2java
 */
@Entity
@Table(name="Curriculo"
    ,catalog="mack"
)
public class Curriculo  implements java.io.Serializable {


     private Integer codCv;
     private Integer codExpProf;
     private Integer cerficado;
     private int codAreaAtuacao;

    public Curriculo() {
    }

	
    public Curriculo(int codAreaAtuacao) {
        this.codAreaAtuacao = codAreaAtuacao;
    }
    public Curriculo(Integer codExpProf, Integer cerficado, int codAreaAtuacao) {
       this.codExpProf = codExpProf;
       this.cerficado = cerficado;
       this.codAreaAtuacao = codAreaAtuacao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="Cod_Cv", unique=true, nullable=false)
    public Integer getCodCv() {
        return this.codCv;
    }
    
    public void setCodCv(Integer codCv) {
        this.codCv = codCv;
    }
    
    @Column(name="Cod_Exp_Prof")
    public Integer getCodExpProf() {
        return this.codExpProf;
    }
    
    public void setCodExpProf(Integer codExpProf) {
        this.codExpProf = codExpProf;
    }
    
    @Column(name="Cerficado")
    public Integer getCerficado() {
        return this.cerficado;
    }
    
    public void setCerficado(Integer cerficado) {
        this.cerficado = cerficado;
    }
    
    @Column(name="Cod_Area_Atuacao", nullable=false)
    public int getCodAreaAtuacao() {
        return this.codAreaAtuacao;
    }
    
    public void setCodAreaAtuacao(int codAreaAtuacao) {
        this.codAreaAtuacao = codAreaAtuacao;
    }




}


