package JPA2;
// Generated Nov 22, 2012 5:49:27 PM by Hibernate Tools 3.2.1.GA



/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Integer codCurso;
     private String descricao;

    public Curso() {
    }

    public Curso(String descricao) {
       this.descricao = descricao;
    }
   
    public Integer getCodCurso() {
        return this.codCurso;
    }
    
    public void setCodCurso(Integer codCurso) {
        this.codCurso = codCurso;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


