package JPA2;
// Generated Oct 27, 2012 12:41:22 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name="Curso"
    ,catalog="mack"
)
public class Curso  implements java.io.Serializable {


     private int codCurso;
     private String descricao;

    public Curso() {
    }

	
    public Curso(int codCurso) {
        this.codCurso = codCurso;
    }
    public Curso(int codCurso, String descricao) {
       this.codCurso = codCurso;
       this.descricao = descricao;
    }
   
     @Id 
    
    @Column(name="Cod_Curso", unique=true, nullable=false)
    public int getCodCurso() {
        return this.codCurso;
    }
    
    public void setCodCurso(int codCurso) {
        this.codCurso = codCurso;
    }
    
    @Column(name="Descricao", length=50)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


