package JPA2;
// Generated Oct 27, 2012 7:04:32 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name="Curso"
    ,catalog="mack"
)
public class Curso  implements java.io.Serializable {


     private Integer codCurso;
     private String descricao;

    public Curso() {
    }

    public Curso(String descricao) {
       this.descricao = descricao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="Cod_Curso", unique=true, nullable=false)
    public Integer getCodCurso() {
        return this.codCurso;
    }
    
    public void setCodCurso(Integer codCurso) {
        this.codCurso = codCurso;
    }
    
    @Column(name="Descricao", length=50)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


