package JPA2;
// Generated Oct 27, 2012 7:04:32 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.*;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name="Empresa"
    ,catalog="mack"
    , uniqueConstraints = @UniqueConstraint(columnNames="CNPJ") 
)
public class Empresa  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy= GenerationType.AUTO)
    @Column(name="Cod_Empresa", unique=true, nullable=false)
     private Integer codEmpresa;
    @Column(name="CNPJ", unique=true, nullable=false, length=15)
     private String cnpj;
    @Column(name="Nome", nullable=false, length=20)
     private String nome;
    @Column(name="Senha", nullable=false, length=10)
     private String senha;

    public Empresa() {
    }

    public Empresa(String cnpj, String nome, String senha) {
       this.cnpj = cnpj;
       this.nome = nome;
       this.senha = senha;
    }
   
         public Integer getCodEmpresa() {
        return this.codEmpresa;
    }
    
    public void setCodEmpresa(Integer codEmpresa) {
        this.codEmpresa = codEmpresa;
    }
    
        public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    
        public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    
        public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


