package JPA2;
// Generated Oct 27, 2012 12:41:22 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name="Empresa"
    ,catalog="mack"
    , uniqueConstraints = @UniqueConstraint(columnNames="CNPJ") 
)
public class Empresa  implements java.io.Serializable {


     private int codEmpresa;
     private String cnpj;
     private String nome;
     private String senha;

    public Empresa() {
    }

    public Empresa(int codEmpresa, String cnpj, String nome, String senha) {
       this.codEmpresa = codEmpresa;
       this.cnpj = cnpj;
       this.nome = nome;
       this.senha = senha;
    }
   
     @Id 
    
    @Column(name="Cod_Empresa", unique=true, nullable=false)
    public int getCodEmpresa() {
        return this.codEmpresa;
    }
    
    public void setCodEmpresa(int codEmpresa) {
        this.codEmpresa = codEmpresa;
    }
    
    @Column(name="CNPJ", unique=true, nullable=false, length=15)
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    
    @Column(name="Nome", nullable=false, length=20)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    
    @Column(name="Senha", nullable=false, length=10)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


