package JPA2;
// Generated Nov 22, 2012 5:49:27 PM by Hibernate Tools 3.2.1.GA



/**
 * ExpProfSistema generated by hbm2java
 */
public class ExpProfSistema  implements java.io.Serializable {


     private Integer codExpProf;
     private String descricao;
     private Integer codEmpresa;
     private Integer codUsr;

    public ExpProfSistema() {
    }

    public ExpProfSistema(String descricao, Integer codEmpresa, Integer codUsr) {
       this.descricao = descricao;
       this.codEmpresa = codEmpresa;
       this.codUsr = codUsr;
    }
   
    public Integer getCodExpProf() {
        return this.codExpProf;
    }
    
    public void setCodExpProf(Integer codExpProf) {
        this.codExpProf = codExpProf;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Integer getCodEmpresa() {
        return this.codEmpresa;
    }
    
    public void setCodEmpresa(Integer codEmpresa) {
        this.codEmpresa = codEmpresa;
    }
    public Integer getCodUsr() {
        return this.codUsr;
    }
    
    public void setCodUsr(Integer codUsr) {
        this.codUsr = codUsr;
    }




}


