package JPA2;
// Generated Oct 27, 2012 12:41:22 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ExpProfSistema generated by hbm2java
 */
@Entity
@Table(name="Exp_Prof_Sistema"
    ,catalog="mack"
)
public class ExpProfSistema  implements java.io.Serializable {


     private int codExpProf;
     private String descricao;
     private Integer codEmpresa;

    public ExpProfSistema() {
    }

	
    public ExpProfSistema(int codExpProf) {
        this.codExpProf = codExpProf;
    }
    public ExpProfSistema(int codExpProf, String descricao, Integer codEmpresa) {
       this.codExpProf = codExpProf;
       this.descricao = descricao;
       this.codEmpresa = codEmpresa;
    }
   
     @Id 
    
    @Column(name="Cod_Exp_Prof", unique=true, nullable=false)
    public int getCodExpProf() {
        return this.codExpProf;
    }
    
    public void setCodExpProf(int codExpProf) {
        this.codExpProf = codExpProf;
    }
    
    @Column(name="Descricao", length=20)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    
    @Column(name="Cod_Empresa")
    public Integer getCodEmpresa() {
        return this.codEmpresa;
    }
    
    public void setCodEmpresa(Integer codEmpresa) {
        this.codEmpresa = codEmpresa;
    }




}


