package JPA2;
// Generated Oct 27, 2012 7:04:32 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.*;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FormacaoAcademica generated by hbm2java
 */
@Entity
@Table(name="Formacao_Academica"
    ,catalog="mack"
)
public class FormacaoAcademica  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy= GenerationType.AUTO)
    @Column(name="Cod_Fa", unique=true, nullable=false)
     private Integer codFa;
    @Column(name="Cod_Usr", nullable=false)
     private int codUsr;
    @Column(name="Cod_Universidade", nullable=false)
     private int codUniversidade;
    @Column(name="Situacao", nullable=false, length=20)
     private String situacao;
    @Column(name="Semestre_Atual", nullable=false)
     private int semestreAtual;
    @Column(name="Semestre_Formacao", nullable=false)
     private int semestreFormacao;
    @Column(name="Ano_Formacao", nullable=false)
     private int anoFormacao;
    @Column(name="Cod_Curso", nullable=false)
     private int codCurso;

    public FormacaoAcademica() {
    }

    public FormacaoAcademica(int codUsr, int codUniversidade, String situacao, int semestreAtual, int semestreFormacao, int anoFormacao, int codCurso) {
       this.codUsr = codUsr;
       this.codUniversidade = codUniversidade;
       this.situacao = situacao;
       this.semestreAtual = semestreAtual;
       this.semestreFormacao = semestreFormacao;
       this.anoFormacao = anoFormacao;
       this.codCurso = codCurso;
    }
   
         public Integer getCodFa() {
        return this.codFa;
    }
    
    public void setCodFa(Integer codFa) {
        this.codFa = codFa;
    }
    
        public int getCodUsr() {
        return this.codUsr;
    }
    
    public void setCodUsr(int codUsr) {
        this.codUsr = codUsr;
    }
    
        public int getCodUniversidade() {
        return this.codUniversidade;
    }
    
    public void setCodUniversidade(int codUniversidade) {
        this.codUniversidade = codUniversidade;
    }
    
        public String getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }
    
        public int getSemestreAtual() {
        return this.semestreAtual;
    }
    
    public void setSemestreAtual(int semestreAtual) {
        this.semestreAtual = semestreAtual;
    }
    
        public int getSemestreFormacao() {
        return this.semestreFormacao;
    }
    
    public void setSemestreFormacao(int semestreFormacao) {
        this.semestreFormacao = semestreFormacao;
    }
    
        public int getAnoFormacao() {
        return this.anoFormacao;
    }
    
    public void setAnoFormacao(int anoFormacao) {
        this.anoFormacao = anoFormacao;
    }
    
        public int getCodCurso() {
        return this.codCurso;
    }
    
    public void setCodCurso(int codCurso) {
        this.codCurso = codCurso;
    }




}


