package JPA2;
// Generated Nov 22, 2012 5:49:27 PM by Hibernate Tools 3.2.1.GA



/**
 * FormacaoAcademica generated by hbm2java
 */
public class FormacaoAcademica  implements java.io.Serializable {


     private Integer codFa;
     private Integer codUsr;
     private Integer codUniversidade;
     private String situacao;
     private Integer semestreAtual;
     private Integer semestreFormacao;
     private Integer anoFormacao;
     private Integer codCurso;

    public FormacaoAcademica() {
    }

    public FormacaoAcademica(Integer codUsr, Integer codUniversidade, String situacao, Integer semestreAtual, Integer semestreFormacao, Integer anoFormacao, Integer codCurso) {
       this.codUsr = codUsr;
       this.codUniversidade = codUniversidade;
       this.situacao = situacao;
       this.semestreAtual = semestreAtual;
       this.semestreFormacao = semestreFormacao;
       this.anoFormacao = anoFormacao;
       this.codCurso = codCurso;
    }
   
    public Integer getCodFa() {
        return this.codFa;
    }
    
    public void setCodFa(Integer codFa) {
        this.codFa = codFa;
    }
    public Integer getCodUsr() {
        return this.codUsr;
    }
    
    public void setCodUsr(Integer codUsr) {
        this.codUsr = codUsr;
    }
    public Integer getCodUniversidade() {
        return this.codUniversidade;
    }
    
    public void setCodUniversidade(Integer codUniversidade) {
        this.codUniversidade = codUniversidade;
    }
    public String getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }
    public Integer getSemestreAtual() {
        return this.semestreAtual;
    }
    
    public void setSemestreAtual(Integer semestreAtual) {
        this.semestreAtual = semestreAtual;
    }
    public Integer getSemestreFormacao() {
        return this.semestreFormacao;
    }
    
    public void setSemestreFormacao(Integer semestreFormacao) {
        this.semestreFormacao = semestreFormacao;
    }
    public Integer getAnoFormacao() {
        return this.anoFormacao;
    }
    
    public void setAnoFormacao(Integer anoFormacao) {
        this.anoFormacao = anoFormacao;
    }
    public Integer getCodCurso() {
        return this.codCurso;
    }
    
    public void setCodCurso(Integer codCurso) {
        this.codCurso = codCurso;
    }




}


