package JPA2;
// Generated Oct 27, 2012 7:04:32 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.*;

/**
 * Universidade generated by hbm2java
 */
@Entity
@Table(name="Universidade"
    ,catalog="mack"
)
public class Universidade  implements java.io.Serializable {

    
     @Id
     @GeneratedValue (strategy= GenerationType.AUTO)
     @Column(name="Cod_Universidade", unique=true, nullable=false)
     private Integer codUniversidade;
     @Column(name="Nome", length=100)
     private String nome;

    public Universidade() {
    }

    public Universidade(String nome) {
       this.nome = nome;
    }
    
        public Integer getCodUniversidade() {
        return this.codUniversidade;
    }
    
    public void setCodUniversidade(Integer codUniversidade) {
        this.codUniversidade = codUniversidade;
    }
    
        public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }




}


