package JPA2;
// Generated Oct 27, 2012 12:41:22 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Universidade generated by hbm2java
 */
@Entity
@Table(name="Universidade"
    ,catalog="mack"
)
public class Universidade  implements java.io.Serializable {


     private int codUniversidade;
     private String nome;

    public Universidade() {
    }

	
    public Universidade(int codUniversidade) {
        this.codUniversidade = codUniversidade;
    }
    public Universidade(int codUniversidade, String nome) {
       this.codUniversidade = codUniversidade;
       this.nome = nome;
    }
   
     @Id 
    
    @Column(name="Cod_Universidade", unique=true, nullable=false)
    public int getCodUniversidade() {
        return this.codUniversidade;
    }
    
    public void setCodUniversidade(int codUniversidade) {
        this.codUniversidade = codUniversidade;
    }
    
    @Column(name="Nome", length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }




}


