package JPA2;
// Generated Nov 22, 2012 5:49:27 PM by Hibernate Tools 3.2.1.GA



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer codUsr;
     private String cpf;
     private String nome;
     private String senha;
     private Integer codCv;
     private Integer codFa;

    public Usuario() {
    }

    public Usuario(String cpf, String nome, String senha, Integer codCv, Integer codFa) {
       this.cpf = cpf;
       this.nome = nome;
       this.senha = senha;
       this.codCv = codCv;
       this.codFa = codFa;
    }
   
    public Integer getCodUsr() {
        return this.codUsr;
    }
    
    public void setCodUsr(Integer codUsr) {
        this.codUsr = codUsr;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Integer getCodCv() {
        return this.codCv;
    }
    
    public void setCodCv(Integer codCv) {
        this.codCv = codCv;
    }
    public Integer getCodFa() {
        return this.codFa;
    }
    
    public void setCodFa(Integer codFa) {
        this.codFa = codFa;
    }




}


