package JPA2;
// Generated Oct 27, 2012 7:04:32 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.*;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="Usuario"
    ,catalog="mack"
    , uniqueConstraints = @UniqueConstraint(columnNames="CPF") 
)
public class Usuario  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy= GenerationType.AUTO)
    @Column(name="Cod_Usr", unique=true, nullable=false)
     private Integer codUsr;
    @Column(name="CPF", unique=true, nullable=false, length=11)
     private String cpf;
    @Column(name="Nome", nullable=false, length=30)
     private String nome;
    @Column(name="Senha", nullable=false, length=10)
     private String senha;
    @Column(name="Cod_Cv")
     private Integer codCv;
    @Column(name="Cod_Fa", nullable=false)
     private int codFa;

    public Usuario() {
    }

	
    public Usuario(String cpf, String nome, String senha, int codFa) {
        this.cpf = cpf;
        this.nome = nome;
        this.senha = senha;
        this.codFa = codFa;
    }
    public Usuario(String cpf, String nome, String senha, Integer codCv, int codFa) {
       this.cpf = cpf;
       this.nome = nome;
       this.senha = senha;
       this.codCv = codCv;
       this.codFa = codFa;
    }
   
    public Integer getCodUsr() {
        return this.codUsr;
    }
    
    public void setCodUsr(Integer codUsr) {
        this.codUsr = codUsr;
    }
    
        public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    
        public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    
        public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    
        public Integer getCodCv() {
        return this.codCv;
    }
    
    public void setCodCv(Integer codCv) {
        this.codCv = codCv;
    }
    
        public int getCodFa() {
        return this.codFa;
    }
    
    public void setCodFa(int codFa) {
        this.codFa = codFa;
    }




}


