package JPA2;
// Generated Nov 22, 2012 5:49:27 PM by Hibernate Tools 3.2.1.GA



/**
 * UsuarioVaga generated by hbm2java
 */
public class UsuarioVaga  implements java.io.Serializable {


     private Integer codUv;
     private Integer codUsr;
     private Integer codVaga;

    public UsuarioVaga() {
    }

    public UsuarioVaga(Integer codUsr, Integer codVaga) {
       this.codUsr = codUsr;
       this.codVaga = codVaga;
    }
   
    public Integer getCodUv() {
        return this.codUv;
    }
    
    public void setCodUv(Integer codUv) {
        this.codUv = codUv;
    }
    public Integer getCodUsr() {
        return this.codUsr;
    }
    
    public void setCodUsr(Integer codUsr) {
        this.codUsr = codUsr;
    }
    public Integer getCodVaga() {
        return this.codVaga;
    }
    
    public void setCodVaga(Integer codVaga) {
        this.codVaga = codVaga;
    }




}


