package JPA2;
// Generated Oct 27, 2012 12:41:22 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="Usuario"
    ,catalog="mack"
    , uniqueConstraints = @UniqueConstraint(columnNames="CPF") 
)
public class Usuario  implements java.io.Serializable {


     private int codUsr;
     private String cpf;
     private String nome;
     private String senha;
     private Integer codCv;
     private int codFa;

    public Usuario() {
    }

	
    public Usuario(int codUsr, String cpf, String nome, String senha, int codFa) {
        this.codUsr = codUsr;
        this.cpf = cpf;
        this.nome = nome;
        this.senha = senha;
        this.codFa = codFa;
    }
    public Usuario(int codUsr, String cpf, String nome, String senha, Integer codCv, int codFa) {
       this.codUsr = codUsr;
       this.cpf = cpf;
       this.nome = nome;
       this.senha = senha;
       this.codCv = codCv;
       this.codFa = codFa;
    }
   
     @Id 
    
    @Column(name="Cod_Usr", unique=true, nullable=false)
    public int getCodUsr() {
        return this.codUsr;
    }
    
    public void setCodUsr(int codUsr) {
        this.codUsr = codUsr;
    }
    
    @Column(name="CPF", unique=true, nullable=false, length=11)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    
    @Column(name="Nome", nullable=false, length=30)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    
    @Column(name="Senha", nullable=false, length=10)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    
    @Column(name="Cod_Cv")
    public Integer getCodCv() {
        return this.codCv;
    }
    
    public void setCodCv(Integer codCv) {
        this.codCv = codCv;
    }
    
    @Column(name="Cod_Fa", nullable=false)
    public int getCodFa() {
        return this.codFa;
    }
    
    public void setCodFa(int codFa) {
        this.codFa = codFa;
    }




}


