package JPA2;
// Generated Oct 27, 2012 7:04:32 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.*;

/**
 * UsuarioVaga generated by hbm2java
 */
@Entity
@Table(name="Usuario_Vaga"
    ,catalog="mack"
)
public class UsuarioVaga  implements java.io.Serializable {

    
     @Id
     @GeneratedValue (strategy= GenerationType.AUTO)
     @Column(name="Cod_Uv", unique=true, nullable=false)
     private Integer codUv;
    @Column(name="Cod_Usr")
     private Integer codUsr;
    @Column(name="Cod_Vaga")
     private Integer codVaga;

    public UsuarioVaga() {
    }

    public UsuarioVaga(Integer codUsr, Integer codVaga) {
       this.codUsr = codUsr;
       this.codVaga = codVaga;
    }
    
        public Integer getCodUv() {
        return this.codUv;
    }
    
    public void setCodUv(Integer codUv) {
        this.codUv = codUv;
    }
    
        public Integer getCodUsr() {
        return this.codUsr;
    }
    
    public void setCodUsr(Integer codUsr) {
        this.codUsr = codUsr;
    }
    
        public Integer getCodVaga() {
        return this.codVaga;
    }
    
    public void setCodVaga(Integer codVaga) {
        this.codVaga = codVaga;
    }




}


