package JPA2;
// Generated Oct 27, 2012 7:04:32 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vagas generated by hbm2java
 */
@Entity
@Table(name="Vagas"
    ,catalog="mack"
)
public class Vagas  implements java.io.Serializable {


     private Integer codVaga;
     private Integer salario;
     private String descricao;
     private int codEmpresa;
     private int codAreaAtuacao;

    public Vagas() {
    }

	
    public Vagas(int codEmpresa, int codAreaAtuacao) {
        this.codEmpresa = codEmpresa;
        this.codAreaAtuacao = codAreaAtuacao;
    }
    public Vagas(Integer salario, String descricao, int codEmpresa, int codAreaAtuacao) {
       this.salario = salario;
       this.descricao = descricao;
       this.codEmpresa = codEmpresa;
       this.codAreaAtuacao = codAreaAtuacao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="Cod_Vaga", unique=true, nullable=false)
    public Integer getCodVaga() {
        return this.codVaga;
    }
    
    public void setCodVaga(Integer codVaga) {
        this.codVaga = codVaga;
    }
    
    @Column(name="Salario")
    public Integer getSalario() {
        return this.salario;
    }
    
    public void setSalario(Integer salario) {
        this.salario = salario;
    }
    
    @Column(name="Descricao", length=50)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    
    @Column(name="Cod_Empresa", nullable=false)
    public int getCodEmpresa() {
        return this.codEmpresa;
    }
    
    public void setCodEmpresa(int codEmpresa) {
        this.codEmpresa = codEmpresa;
    }
    
    @Column(name="Cod_Area_Atuacao", nullable=false)
    public int getCodAreaAtuacao() {
        return this.codAreaAtuacao;
    }
    
    public void setCodAreaAtuacao(int codAreaAtuacao) {
        this.codAreaAtuacao = codAreaAtuacao;
    }




}


